name: Rust Build

on:
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable
    - run: rustup component add clippy
      name: Build
    - run: cargo build --release


